services:
  openaitts:
    image: travisvn/openai-edge-tts:canary
    container_name: openai-edge-tts
    environment:
      - API_KEY=1
      - DEFAULT_VOICE=en-GB-SoniaNeural
      - DEFAULT_RESPONSE_FORMAT=mp3
      - DEFAULT_SPEED=1.0
      - DEFAULT_LANGUAGE=en-US
      - REQUIRE_API_KEY=false
    ports:
      - ${APP_PORT}:5050
    restart: unless-stopped
    networks:
      - tipi_main_network
    labels:
      traefik.enable: true
      traefik.http.middlewares.openai-edge-tts-web-redirect.redirectscheme.scheme: https
      traefik.http.services.openai-edge-tts.loadbalancer.server.port: 5050
      traefik.http.routers.openai-edge-tts-insecure.rule: 'Host(`${APP_DOMAIN}`)'
      traefik.http.routers.openai-edge-tts-insecure.entrypoints: web
      traefik.http.routers.openai-edge-tts-insecure.service: openai-edge-tts
      traefik.http.routers.openai-edge-tts-insecure.middlewares: openai-edge-tts-web-redirect
      traefik.http.routers.openai-edge-tts.rule: 'Host(`${APP_DOMAIN}`)'
      traefik.http.routers.openai-edge-tts.entrypoints: websecure
      traefik.http.routers.openai-edge-tts.service: openai-edge-tts
      traefik.http.routers.openai-edge-tts.tls.certresolver: myresolver
      traefik.http.routers.openai-edge-tts-local-insecure.rule: 'Host(`openai-edge-tts.${LOCAL_DOMAIN}`)'
      traefik.http.routers.openai-edge-tts-local-insecure.entrypoints: web
      traefik.http.routers.openai-edge-tts-local-insecure.service: openai-edge-tts
      traefik.http.routers.openai-edge-tts-local-insecure.middlewares: openai-edge-tts-web-redirect
      traefik.http.routers.openai-edge-tts-local.rule: 'Host(`openai-edge-tts.${LOCAL_DOMAIN}`)'
      traefik.http.routers.openai-edge-tts-local.entrypoints: websecure
      traefik.http.routers.openai-edge-tts-local.service: openai-edge-tts
      traefik.http.routers.openai-edge-tts-local.tls: true
      runtipi.managed: true
